spring:
  application:
    name: spring-batch-lecture
  profiles:
    active: mysql
---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  batch:
    job:
      # hard coding ex: job
      # ${job.name:NONE}: program arguments --job.name=job1,job2
      names: ${job.name:NONE}
      enabled: true # auto run
    jdbc:
      initialize-schema: always # schema auto create
      table-prefix: SYSTEM_
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1qaz@WSX
      driver-class-name: com.mysql.cj.jdbc.Driver
